# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno


# CXXFLAGS_STD  = -std=gnu++11 -fno-threadsafe-statics -ffunction-sections -fdata-sections 

include $(ARDMK_DIR)/Arduino.mk
